# Get the dataset


In [1]:
import csv
import numpy as np
import config

test_image = np.load(config.t_path)
test_names = np.load(config.n_path)

assert(test_image.shape[0] == test_names.shape[0])


/home/phuonghd/.conda/envs/nhatenv/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# Boilerplate Code

In [2]:
import torch
from typing import Tuple
class Data(torch.utils.data.Dataset):
    def __init__(self, image: np.ndarray, name: np.ndarray) -> None:
        assert(image.shape[0] == name.shape[0])
        self.image = image
        self.name = name
    
    def __len__(self) -> int:
        return self.image.shape[0]
    
    def __getitem__(self, idx: int) -> 'Tuple[np.ndarray, str]':
        return self.image[idx], self.name[idx]


# Model

In [3]:
model = config.get_model()
model.load_state_dict(torch.load(config.model_path))

use_cuda = torch.cuda.is_available()
if not use_cuda:
    print("CUDA not used!")
device = torch.device("cuda" if use_cuda else "cpu")

model = model.to(device)


# Run tests

In [4]:
from tqdm import tqdm

tests = Data(test_image, test_names)
tests_dataloader = torch.utils.data.DataLoader(
    tests, batch_size = config.batch_size)


with torch.no_grad(), open("result.csv", "w", newline='') as result:
    result_writer = csv.writer(result)
    for image, names in tqdm(tests_dataloader):
        image = image.to(device, dtype=torch.float)

        output = model(image)
        output = output.argmax(dim=1).cpu().item()
        assert(output.shape[0] == names.shape[0])
        
        result_writer.writerows(zip(names, output))


  1%|          | 3/296 [00:03<04:11,  1.17it/s]

('frame_000000.PNG', 'frame_000001.PNG', 'frame_000002.PNG', 'frame_000003.PNG', 'frame_000004.PNG', 'frame_000005.PNG', 'frame_000006.PNG', 'frame_000007.PNG', 'frame_000008.PNG', 'frame_000009.PNG', 'frame_000010.PNG', 'frame_000011.PNG', 'frame_000012.PNG', 'frame_000013.PNG', 'frame_000014.PNG', 'frame_000015.PNG', 'frame_000016.PNG', 'frame_000017.PNG', 'frame_000018.PNG', 'frame_000019.PNG', 'frame_000020.PNG', 'frame_000021.PNG', 'frame_000022.PNG', 'frame_000023.PNG', 'frame_000024.PNG', 'frame_000025.PNG', 'frame_000026.PNG', 'frame_000027.PNG', 'frame_000028.PNG', 'frame_000029.PNG', 'frame_000030.PNG', 'frame_000031.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000032.PNG', 'frame_000033.PNG', 'frame_000034.PNG', 'frame_000035.PNG', 'frame_000036.PNG', 'frame_000037.PNG', 'frame_000038.PNG', 'frame_000039.PNG', 'frame_000040.PNG', 'frame_000041.PNG', 'frame_000042.PNG', 'frame_0

  2%|▏         | 5/296 [00:03<02:09,  2.25it/s]

('frame_000096.PNG', 'frame_000097.PNG', 'frame_000098.PNG', 'frame_000099.PNG', 'frame_000100.PNG', 'frame_000101.PNG', 'frame_000102.PNG', 'frame_000103.PNG', 'frame_000104.PNG', 'frame_000105.PNG', 'frame_000106.PNG', 'frame_000107.PNG', 'frame_000108.PNG', 'frame_000109.PNG', 'frame_000110.PNG', 'frame_000111.PNG', 'frame_000112.PNG', 'frame_000113.PNG', 'frame_000114.PNG', 'frame_000115.PNG', 'frame_000116.PNG', 'frame_000117.PNG', 'frame_000118.PNG', 'frame_000119.PNG', 'frame_000120.PNG', 'frame_000121.PNG', 'frame_000122.PNG', 'frame_000123.PNG', 'frame_000124.PNG', 'frame_000125.PNG', 'frame_000126.PNG', 'frame_000127.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000128.PNG', 'frame_000129.PNG', 'frame_000130.PNG', 'frame_000131.PNG', 'frame_000132.PNG', 'frame_000133.PNG', 'frame_000134.PNG', 'frame_000135.PNG', 'frame_000136.PNG', 'frame_000137.PNG', 'frame_000138.PNG', 'frame_0

  4%|▎         | 11/296 [00:03<00:43,  6.53it/s]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000256.PNG', 'frame_000257.PNG', 'frame_000258.PNG', 'frame_000259.PNG', 'frame_000260.PNG', 'frame_000261.PNG', 'frame_000262.PNG', 'frame_000263.PNG', 'frame_000264.PNG', 'frame_000265.PNG', 'frame_000266.PNG', 'frame_000267.PNG', 'frame_000268.PNG', 'frame_000269.PNG', 'frame_000270.PNG', 'frame_000271.PNG', 'frame_000272.PNG', 'frame_000273.PNG', 'frame_000274.PNG', 'frame_000275.PNG', 'frame_000276.PNG', 'frame_000277.PNG', 'frame_000278.PNG', 'frame_000279.PNG', 'frame_000280.PNG', 'frame_000281.PNG', 'frame_000282.PNG', 'frame_000283.PNG', 'frame_000284.PNG', 'frame_000285.PNG', 'frame_000286.PNG', 'frame_000287.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000288.PNG', 'frame_000289.PNG', 'frame_000290.PNG', 'frame_000291.PNG', 'frame_000292.PNG'

  6%|▌         | 17/296 [00:03<00:23, 11.87it/s]

('frame_000416.PNG', 'frame_000417.PNG', 'frame_000418.PNG', 'frame_000419.PNG', 'frame_000420.PNG', 'frame_000421.PNG', 'frame_000422.PNG', 'frame_000423.PNG', 'frame_000424.PNG', 'frame_000425.PNG', 'frame_000426.PNG', 'frame_000427.PNG', 'frame_000428.PNG', 'frame_000429.PNG', 'frame_000430.PNG', 'frame_000431.PNG', 'frame_000432.PNG', 'frame_000433.PNG', 'frame_000434.PNG', 'frame_000435.PNG', 'frame_000436.PNG', 'frame_000437.PNG', 'frame_000438.PNG', 'frame_000439.PNG', 'frame_000440.PNG', 'frame_000441.PNG', 'frame_000442.PNG', 'frame_000443.PNG', 'frame_000444.PNG', 'frame_000445.PNG', 'frame_000446.PNG', 'frame_000447.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000448.PNG', 'frame_000449.PNG', 'frame_000450.PNG', 'frame_000451.PNG', 'frame_000452.PNG', 'frame_000453.PNG', 'frame_000454.PNG', 'frame_000455.PNG', 'frame_000456.PNG', 'frame_000457.PNG', 'frame_000458.PNG', 'frame_0

  8%|▊         | 23/296 [00:04<00:15, 17.11it/s]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000608.PNG', 'frame_000609.PNG', 'frame_000610.PNG', 'frame_000611.PNG', 'frame_000612.PNG', 'frame_000613.PNG', 'frame_000614.PNG', 'frame_000615.PNG', 'frame_000616.PNG', 'frame_000617.PNG', 'frame_000618.PNG', 'frame_000619.PNG', 'frame_000620.PNG', 'frame_000621.PNG', 'frame_000622.PNG', 'frame_000623.PNG', 'frame_000624.PNG', 'frame_000625.PNG', 'frame_000626.PNG', 'frame_000627.PNG', 'frame_000628.PNG', 'frame_000629.PNG', 'frame_000630.PNG', 'frame_000631.PNG', 'frame_000632.PNG', 'frame_000633.PNG', 'frame_000634.PNG', 'frame_000635.PNG', 'frame_000636.PNG', 'frame_000637.PNG', 'frame_000638.PNG', 'frame_000639.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000640.PNG', 'frame_000641.PNG', 'frame_000642.PNG', 'frame_000643.PNG', 'frame_000644.PNG'

 10%|▉         | 29/296 [00:04<00:12, 21.03it/s]

('frame_000768.PNG', 'frame_000769.PNG', 'frame_000770.PNG', 'frame_000771.PNG', 'frame_000772.PNG', 'frame_000773.PNG', 'frame_000774.PNG', 'frame_000775.PNG', 'frame_000776.PNG', 'frame_000777.PNG', 'frame_000778.PNG', 'frame_000779.PNG', 'frame_000780.PNG', 'frame_000781.PNG', 'frame_000782.PNG', 'frame_000783.PNG', 'frame_000784.PNG', 'frame_000785.PNG', 'frame_000786.PNG', 'frame_000787.PNG', 'frame_000788.PNG', 'frame_000789.PNG', 'frame_000790.PNG', 'frame_000791.PNG', 'frame_000792.PNG', 'frame_000793.PNG', 'frame_000794.PNG', 'frame_000795.PNG', 'frame_000796.PNG', 'frame_000797.PNG', 'frame_000798.PNG', 'frame_000799.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000800.PNG', 'frame_000801.PNG', 'frame_000802.PNG', 'frame_000803.PNG', 'frame_000804.PNG', 'frame_000805.PNG', 'frame_000806.PNG', 'frame_000807.PNG', 'frame_000808.PNG', 'frame_000809.PNG', 'frame_000810.PNG', 'frame_0

 12%|█▏        | 35/296 [00:04<00:10, 23.91it/s]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000960.PNG', 'frame_000961.PNG', 'frame_000962.PNG', 'frame_000963.PNG', 'frame_000964.PNG', 'frame_000965.PNG', 'frame_000966.PNG', 'frame_000967.PNG', 'frame_000968.PNG', 'frame_000969.PNG', 'frame_000970.PNG', 'frame_000971.PNG', 'frame_000972.PNG', 'frame_000973.PNG', 'frame_000974.PNG', 'frame_000975.PNG', 'frame_000976.PNG', 'frame_000977.PNG', 'frame_000978.PNG', 'frame_000979.PNG', 'frame_000980.PNG', 'frame_000981.PNG', 'frame_000982.PNG', 'frame_000983.PNG', 'frame_000984.PNG', 'frame_000985.PNG', 'frame_000986.PNG', 'frame_000987.PNG', 'frame_000988.PNG', 'frame_000989.PNG', 'frame_000990.PNG', 'frame_000991.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000992.PNG', 'frame_000993.PNG', 'frame_000994.PNG', 'frame_000995.PNG', 'frame_000996.PNG'

 14%|█▍        | 41/296 [00:04<00:10, 25.30it/s]

('frame_001120.PNG', 'frame_001121.PNG', 'frame_001122.PNG', 'frame_001123.PNG', 'frame_001124.PNG', 'frame_001125.PNG', 'frame_001126.PNG', 'frame_001127.PNG', 'frame_001128.PNG', 'frame_001129.PNG', 'frame_001130.PNG', 'frame_001131.PNG', 'frame_001132.PNG', 'frame_001133.PNG', 'frame_001134.PNG', 'frame_001135.PNG', 'frame_001136.PNG', 'frame_001137.PNG', 'frame_001138.PNG', 'frame_001139.PNG', 'frame_001140.PNG', 'frame_001141.PNG', 'frame_001142.PNG', 'frame_001143.PNG', 'frame_001144.PNG', 'frame_001145.PNG', 'frame_001146.PNG', 'frame_001147.PNG', 'frame_001148.PNG', 'frame_001149.PNG', 'frame_001150.PNG', 'frame_001151.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_001152.PNG', 'frame_001153.PNG', 'frame_001154.PNG', 'frame_001155.PNG', 'frame_001156.PNG', 'frame_001157.PNG', 'frame_001158.PNG', 'frame_001159.PNG', 'frame_001160.PNG', 'frame_001161.PNG', 'frame_001162.PNG', 'frame_0

 15%|█▍        | 44/296 [00:04<00:09, 25.73it/s]

('frame_001312.PNG', 'frame_001313.PNG', 'frame_001314.PNG', 'frame_001315.PNG', 'frame_001316.PNG', 'frame_001317.PNG', 'frame_001318.PNG', 'frame_001319.PNG', 'frame_001320.PNG', 'frame_001321.PNG', 'frame_001322.PNG', 'frame_001323.PNG', 'frame_001324.PNG', 'frame_001325.PNG', 'frame_001326.PNG', 'frame_001327.PNG', 'frame_001328.PNG', 'frame_001329.PNG', 'frame_001330.PNG', 'frame_001331.PNG', 'frame_001332.PNG', 'frame_001333.PNG', 'frame_001334.PNG', 'frame_001335.PNG', 'frame_001336.PNG', 'frame_001337.PNG', 'frame_001338.PNG', 'frame_001339.PNG', 'frame_001340.PNG', 'frame_001341.PNG', 'frame_001342.PNG', 'frame_001343.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_001344.PNG', 'frame_001345.PNG', 'frame_001346.PNG', 'frame_001347.PNG', 'frame_000000.PNG', 'frame_000001.PNG', 'frame_000002.PNG', 'frame_000003.PNG', 'frame_000004.PNG', 'frame_000005.PNG', 'frame_000006.PNG', 'frame_0

 17%|█▋        | 50/296 [00:05<00:09, 26.09it/s]

('frame_000156.PNG', 'frame_000157.PNG', 'frame_000158.PNG', 'frame_000159.PNG', 'frame_000160.PNG', 'frame_000161.PNG', 'frame_000162.PNG', 'frame_000163.PNG', 'frame_000164.PNG', 'frame_000165.PNG', 'frame_000166.PNG', 'frame_000167.PNG', 'frame_000168.PNG', 'frame_000169.PNG', 'frame_000170.PNG', 'frame_000171.PNG', 'frame_000172.PNG', 'frame_000173.PNG', 'frame_000174.PNG', 'frame_000175.PNG', 'frame_000176.PNG', 'frame_000177.PNG', 'frame_000178.PNG', 'frame_000179.PNG', 'frame_000180.PNG', 'frame_000181.PNG', 'frame_000182.PNG', 'frame_000183.PNG', 'frame_000184.PNG', 'frame_000185.PNG', 'frame_000186.PNG', 'frame_000187.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000188.PNG', 'frame_000189.PNG', 'frame_000190.PNG', 'frame_000191.PNG', 'frame_000192.PNG', 'frame_000193.PNG', 'frame_000194.PNG', 'frame_000195.PNG', 'frame_000196.PNG', 'frame_000197.PNG', 'frame_000198.PNG', 'frame_0

 20%|█▉        | 59/296 [00:05<00:08, 26.64it/s]

('frame_000348.PNG', 'frame_000349.PNG', 'frame_000350.PNG', 'frame_000351.PNG', 'frame_000352.PNG', 'frame_000353.PNG', 'frame_000354.PNG', 'frame_000355.PNG', 'frame_000356.PNG', 'frame_000357.PNG', 'frame_000358.PNG', 'frame_000359.PNG', 'frame_000360.PNG', 'frame_000361.PNG', 'frame_000362.PNG', 'frame_000363.PNG', 'frame_000364.PNG', 'frame_000365.PNG', 'frame_000366.PNG', 'frame_000367.PNG', 'frame_000368.PNG', 'frame_000369.PNG', 'frame_000370.PNG', 'frame_000371.PNG', 'frame_000372.PNG', 'frame_000373.PNG', 'frame_000374.PNG', 'frame_000375.PNG', 'frame_000376.PNG', 'frame_000377.PNG', 'frame_000378.PNG', 'frame_000379.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000380.PNG', 'frame_000381.PNG', 'frame_000382.PNG', 'frame_000383.PNG', 'frame_000384.PNG', 'frame_000385.PNG', 'frame_000386.PNG', 'frame_000387.PNG', 'frame_000388.PNG', 'frame_000389.PNG', 'frame_000390.PNG', 'frame_0

 22%|██▏       | 65/296 [00:05<00:08, 26.99it/s]

('frame_000540.PNG', 'frame_000541.PNG', 'frame_000542.PNG', 'frame_000543.PNG', 'frame_000544.PNG', 'frame_000545.PNG', 'frame_000546.PNG', 'frame_000547.PNG', 'frame_000548.PNG', 'frame_000549.PNG', 'frame_000550.PNG', 'frame_000551.PNG', 'frame_000552.PNG', 'frame_000553.PNG', 'frame_000554.PNG', 'frame_000555.PNG', 'frame_000556.PNG', 'frame_000557.PNG', 'frame_000558.PNG', 'frame_000559.PNG', 'frame_000560.PNG', 'frame_000561.PNG', 'frame_000562.PNG', 'frame_000563.PNG', 'frame_000564.PNG', 'frame_000565.PNG', 'frame_000566.PNG', 'frame_000567.PNG', 'frame_000568.PNG', 'frame_000569.PNG', 'frame_000570.PNG', 'frame_000571.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000572.PNG', 'frame_000573.PNG', 'frame_000574.PNG', 'frame_000575.PNG', 'frame_000576.PNG', 'frame_000577.PNG', 'frame_000578.PNG', 'frame_000579.PNG', 'frame_000580.PNG', 'frame_000581.PNG', 'frame_000582.PNG', 'frame_0

 23%|██▎       | 68/296 [00:05<00:08, 26.89it/s]

('frame_000732.PNG', 'frame_000733.PNG', 'frame_000734.PNG', 'frame_000735.PNG', 'frame_000736.PNG', 'frame_000737.PNG', 'frame_000738.PNG', 'frame_000739.PNG', 'frame_000740.PNG', 'frame_000741.PNG', 'frame_000742.PNG', 'frame_000743.PNG', 'frame_000744.PNG', 'frame_000745.PNG', 'frame_000746.PNG', 'frame_000747.PNG', 'frame_000748.PNG', 'frame_000749.PNG', 'frame_000750.PNG', 'frame_000751.PNG', 'frame_000752.PNG', 'frame_000753.PNG', 'frame_000754.PNG', 'frame_000755.PNG', 'frame_000756.PNG', 'frame_000757.PNG', 'frame_000758.PNG', 'frame_000759.PNG', 'frame_000760.PNG', 'frame_000761.PNG', 'frame_000762.PNG', 'frame_000763.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000764.PNG', 'frame_000765.PNG', 'frame_000766.PNG', 'frame_000767.PNG', 'frame_000768.PNG', 'frame_000769.PNG', 'frame_000770.PNG', 'frame_000771.PNG', 'frame_000772.PNG', 'frame_000773.PNG', 'frame_000774.PNG', 'frame_0

 26%|██▌       | 77/296 [00:06<00:08, 27.11it/s]

('frame_000924.PNG', 'frame_000925.PNG', 'frame_000926.PNG', 'frame_000927.PNG', 'frame_000928.PNG', 'frame_000929.PNG', 'frame_000930.PNG', 'frame_000931.PNG', 'frame_000932.PNG', 'frame_000933.PNG', 'frame_000934.PNG', 'frame_000935.PNG', 'frame_000936.PNG', 'frame_000937.PNG', 'frame_000938.PNG', 'frame_000939.PNG', 'frame_000940.PNG', 'frame_000941.PNG', 'frame_000942.PNG', 'frame_000943.PNG', 'frame_000944.PNG', 'frame_000945.PNG', 'frame_000946.PNG', 'frame_000947.PNG', 'frame_000948.PNG', 'frame_000949.PNG', 'frame_000950.PNG', 'frame_000951.PNG', 'frame_000952.PNG', 'frame_000953.PNG', 'frame_000954.PNG', 'frame_000955.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000956.PNG', 'frame_000957.PNG', 'frame_000958.PNG', 'frame_000959.PNG', 'frame_000960.PNG', 'frame_000961.PNG', 'frame_000962.PNG', 'frame_000963.PNG', 'frame_000964.PNG', 'frame_000965.PNG', 'frame_000966.PNG', 'frame_0

 28%|██▊       | 83/296 [00:06<00:07, 27.63it/s]

('frame_001116.PNG', 'frame_001117.PNG', 'frame_001118.PNG', 'frame_001119.PNG', 'frame_001120.PNG', 'frame_001121.PNG', 'frame_001122.PNG', 'frame_001123.PNG', 'frame_001124.PNG', 'frame_001125.PNG', 'frame_001126.PNG', 'frame_001127.PNG', 'frame_001128.PNG', 'frame_001129.PNG', 'frame_001130.PNG', 'frame_001131.PNG', 'frame_001132.PNG', 'frame_001133.PNG', 'frame_001134.PNG', 'frame_001135.PNG', 'frame_001136.PNG', 'frame_001137.PNG', 'frame_001138.PNG', 'frame_001139.PNG', 'frame_001140.PNG', 'frame_001141.PNG', 'frame_001142.PNG', 'frame_001143.PNG', 'frame_001144.PNG', 'frame_001145.PNG', 'frame_001146.PNG', 'frame_001147.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_001148.PNG', 'frame_001149.PNG', 'frame_001150.PNG', 'frame_001151.PNG', 'frame_001152.PNG', 'frame_001153.PNG', 'frame_001154.PNG', 'frame_001155.PNG', 'frame_001156.PNG', 'frame_001157.PNG', 'frame_001158.PNG', 'frame_0

 30%|███       | 89/296 [00:06<00:07, 27.25it/s]

('frame_001308.PNG', 'frame_001309.PNG', 'frame_001310.PNG', 'frame_001311.PNG', 'frame_001312.PNG', 'frame_001313.PNG', 'frame_001314.PNG', 'frame_001315.PNG', 'frame_001316.PNG', 'frame_001317.PNG', 'frame_001318.PNG', 'frame_001319.PNG', 'frame_001320.PNG', 'frame_001321.PNG', 'frame_001322.PNG', 'frame_001323.PNG', 'frame_001324.PNG', 'frame_001325.PNG', 'frame_001326.PNG', 'frame_001327.PNG', 'frame_001328.PNG', 'frame_001329.PNG', 'frame_001330.PNG', 'frame_001331.PNG', 'frame_001332.PNG', 'frame_001333.PNG', 'frame_001334.PNG', 'frame_001335.PNG', 'frame_001336.PNG', 'frame_001337.PNG', 'frame_001338.PNG', 'frame_001339.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_001340.PNG', 'frame_001341.PNG', 'frame_001342.PNG', 'frame_001343.PNG', 'frame_001344.PNG', 'frame_001345.PNG', 'frame_001346.PNG', 'frame_001347.PNG', 'frame_001348.PNG', 'frame_001349.PNG', 'frame_001350.PNG', 'frame_0

 32%|███▏      | 95/296 [00:06<00:07, 26.97it/s]

('frame_007999.PNG', 'frame_008000.PNG', 'frame_008001.PNG', 'frame_008002.PNG', 'frame_008003.PNG', 'frame_008004.PNG', 'frame_008005.PNG', 'frame_008006.PNG', 'frame_008007.PNG', 'frame_008008.PNG', 'frame_008009.PNG', 'frame_008010.PNG', 'frame_008011.PNG', 'frame_008012.PNG', 'frame_008013.PNG', 'frame_008014.PNG', 'frame_008015.PNG', 'frame_008016.PNG', 'frame_008017.PNG', 'frame_008018.PNG', 'frame_008019.PNG', 'frame_008020.PNG', 'frame_008021.PNG', 'frame_008022.PNG', 'frame_008023.PNG', 'frame_008024.PNG', 'frame_008025.PNG', 'frame_008026.PNG', 'frame_008027.PNG', 'frame_008028.PNG', 'frame_008029.PNG', 'frame_008030.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_008031.PNG', 'frame_008032.PNG', 'frame_008033.PNG', 'frame_008034.PNG', 'frame_008035.PNG', 'frame_008036.PNG', 'frame_008037.PNG', 'frame_008038.PNG', 'frame_008039.PNG', 'frame_008040.PNG', 'frame_008041.PNG', 'frame_0

 33%|███▎      | 98/296 [00:06<00:07, 26.77it/s]

('frame_008191.PNG', 'frame_008192.PNG', 'frame_008193.PNG', 'frame_008194.PNG', 'frame_008195.PNG', 'frame_008196.PNG', 'frame_008197.PNG', 'frame_008198.PNG', 'frame_008199.PNG', 'frame_008200.PNG', 'frame_008201.PNG', 'frame_008202.PNG', 'frame_008203.PNG', 'frame_008204.PNG', 'frame_008205.PNG', 'frame_008206.PNG', 'frame_008207.PNG', 'frame_008208.PNG', 'frame_008209.PNG', 'frame_008210.PNG', 'frame_008211.PNG', 'frame_008212.PNG', 'frame_008213.PNG', 'frame_008214.PNG', 'frame_008215.PNG', 'frame_008216.PNG', 'frame_008217.PNG', 'frame_008218.PNG', 'frame_008219.PNG', 'frame_008220.PNG', 'frame_008221.PNG', 'frame_008222.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_008223.PNG', 'frame_008224.PNG', 'frame_008225.PNG', 'frame_008226.PNG', 'frame_008227.PNG', 'frame_008228.PNG', 'frame_008229.PNG', 'frame_008230.PNG', 'frame_008231.PNG', 'frame_008232.PNG', 'frame_008233.PNG', 'frame_0

 35%|███▌      | 104/296 [00:07<00:07, 26.77it/s]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_008383.PNG', 'frame_008384.PNG', 'frame_008385.PNG', 'frame_008386.PNG', 'frame_008387.PNG', 'frame_008388.PNG', 'frame_008389.PNG', 'frame_008390.PNG', 'frame_008391.PNG', 'frame_008392.PNG', 'frame_008393.PNG', 'frame_008394.PNG', 'frame_008395.PNG', 'frame_008396.PNG', 'frame_008397.PNG', 'frame_008398.PNG', 'frame_008399.PNG', 'frame_008400.PNG', 'frame_008401.PNG', 'frame_008402.PNG', 'frame_008403.PNG', 'frame_008404.PNG', 'frame_008405.PNG', 'frame_008406.PNG', 'frame_008407.PNG', 'frame_008408.PNG', 'frame_008409.PNG', 'frame_008410.PNG', 'frame_008411.PNG', 'frame_008412.PNG', 'frame_008413.PNG', 'frame_008414.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_008415.PNG', 'frame_008416.PNG', 'frame_008417.PNG', 'frame_008418.PNG', 'frame_008419.PNG'

 37%|███▋      | 110/296 [00:07<00:07, 26.02it/s]

('frame_008543.PNG', 'frame_008544.PNG', 'frame_008545.PNG', 'frame_008546.PNG', 'frame_008547.PNG', 'frame_008548.PNG', 'frame_008549.PNG', 'frame_008550.PNG', 'frame_008551.PNG', 'frame_008552.PNG', 'frame_008553.PNG', 'frame_008554.PNG', 'frame_008555.PNG', 'frame_008556.PNG', 'frame_008557.PNG', 'frame_008558.PNG', 'frame_008559.PNG', 'frame_008560.PNG', 'frame_008561.PNG', 'frame_008562.PNG', 'frame_008563.PNG', 'frame_008564.PNG', 'frame_008565.PNG', 'frame_008566.PNG', 'frame_008567.PNG', 'frame_008568.PNG', 'frame_008569.PNG', 'frame_008570.PNG', 'frame_008571.PNG', 'frame_008572.PNG', 'frame_008573.PNG', 'frame_008574.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_008575.PNG', 'frame_008576.PNG', 'frame_008577.PNG', 'frame_008578.PNG', 'frame_008579.PNG', 'frame_008580.PNG', 'frame_008581.PNG', 'frame_008582.PNG', 'frame_008583.PNG', 'frame_008584.PNG', 'frame_008585.PNG', 'frame_0

 39%|███▉      | 116/296 [00:07<00:06, 26.45it/s]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_008735.PNG', 'frame_008736.PNG', 'frame_008737.PNG', 'frame_008738.PNG', 'frame_008739.PNG', 'frame_008740.PNG', 'frame_008741.PNG', 'frame_008742.PNG', 'frame_008743.PNG', 'frame_008744.PNG', 'frame_008745.PNG', 'frame_008746.PNG', 'frame_008747.PNG', 'frame_008748.PNG', 'frame_008749.PNG', 'frame_008750.PNG', 'frame_008751.PNG', 'frame_008752.PNG', 'frame_008753.PNG', 'frame_008754.PNG', 'frame_008755.PNG', 'frame_008756.PNG', 'frame_008757.PNG', 'frame_008758.PNG', 'frame_008759.PNG', 'frame_008760.PNG', 'frame_008761.PNG', 'frame_008762.PNG', 'frame_008763.PNG', 'frame_008764.PNG', 'frame_008765.PNG', 'frame_008766.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_008767.PNG', 'frame_008768.PNG', 'frame_008769.PNG', 'frame_008770.PNG', 'frame_008771.PNG'

 40%|████      | 119/296 [00:07<00:06, 26.45it/s]

('frame_008895.PNG', 'frame_008896.PNG', 'frame_008897.PNG', 'frame_008898.PNG', 'frame_008899.PNG', 'frame_008900.PNG', 'frame_008901.PNG', 'frame_008902.PNG', 'frame_008903.PNG', 'frame_008904.PNG', 'frame_008905.PNG', 'frame_008906.PNG', 'frame_008907.PNG', 'frame_008908.PNG', 'frame_008909.PNG', 'frame_008910.PNG', 'frame_008911.PNG', 'frame_008912.PNG', 'frame_008913.PNG', 'frame_008914.PNG', 'frame_008915.PNG', 'frame_008916.PNG', 'frame_008917.PNG', 'frame_008918.PNG', 'frame_008919.PNG', 'frame_008920.PNG', 'frame_008921.PNG', 'frame_008922.PNG', 'frame_008923.PNG', 'frame_008924.PNG', 'frame_008925.PNG', 'frame_008926.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_008927.PNG', 'frame_008928.PNG', 'frame_008929.PNG', 'frame_008930.PNG', 'frame_008931.PNG', 'frame_008932.PNG', 'frame_008933.PNG', 'frame_008934.PNG', 'frame_008935.PNG', 'frame_008936.PNG', 'frame_008937.PNG', 'frame_0

 42%|████▏     | 125/296 [00:07<00:07, 22.23it/s]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_001336.PNG', 'frame_001337.PNG', 'frame_001338.PNG', 'frame_001339.PNG', 'frame_001340.PNG', 'frame_001341.PNG', 'frame_001342.PNG', 'frame_001343.PNG', 'frame_001344.PNG', 'frame_001345.PNG', 'frame_001346.PNG', 'frame_001347.PNG', 'frame_001348.PNG', 'frame_001349.PNG', 'frame_001350.PNG', 'frame_001351.PNG', 'frame_001352.PNG', 'frame_001353.PNG', 'frame_001354.PNG', 'frame_001355.PNG', 'frame_001356.PNG', 'frame_001357.PNG', 'frame_001358.PNG', 'frame_001359.PNG', 'frame_001360.PNG', 'frame_001361.PNG', 'frame_001362.PNG', 'frame_001363.PNG', 'frame_001364.PNG', 'frame_001365.PNG', 'frame_001366.PNG', 'frame_001367.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_001368.PNG', 'frame_001369.PNG', 'frame_001370.PNG', 'frame_001371.PNG', 'frame_001372.PNG'

 44%|████▍     | 131/296 [00:08<00:07, 22.95it/s]

('frame_001464.PNG', 'frame_001465.PNG', 'frame_001466.PNG', 'frame_001467.PNG', 'frame_001468.PNG', 'frame_001469.PNG', 'frame_001470.PNG', 'frame_001471.PNG', 'frame_001472.PNG', 'frame_001473.PNG', 'frame_001474.PNG', 'frame_001475.PNG', 'frame_001476.PNG', 'frame_001477.PNG', 'frame_001478.PNG', 'frame_001479.PNG', 'frame_001480.PNG', 'frame_001481.PNG', 'frame_001482.PNG', 'frame_001483.PNG', 'frame_001484.PNG', 'frame_001485.PNG', 'frame_001486.PNG', 'frame_001487.PNG', 'frame_001488.PNG', 'frame_001489.PNG', 'frame_001490.PNG', 'frame_001491.PNG', 'frame_001492.PNG', 'frame_001493.PNG', 'frame_001494.PNG', 'frame_001495.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_001496.PNG', 'frame_001497.PNG', 'frame_001498.PNG', 'frame_001499.PNG', 'frame_001500.PNG', 'frame_001501.PNG', 'frame_001502.PNG', 'frame_001503.PNG', 'frame_001504.PNG', 'frame_001505.PNG', 'frame_001506.PNG', 'frame_0

 46%|████▋     | 137/296 [00:08<00:06, 24.51it/s]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_001656.PNG', 'frame_001657.PNG', 'frame_001658.PNG', 'frame_001659.PNG', 'frame_001660.PNG', 'frame_001661.PNG', 'frame_001662.PNG', 'frame_001663.PNG', 'frame_001664.PNG', 'frame_001665.PNG', 'frame_001666.PNG', 'frame_001667.PNG', 'frame_001668.PNG', 'frame_001669.PNG', 'frame_001670.PNG', 'frame_001671.PNG', 'frame_001672.PNG', 'frame_001673.PNG', 'frame_001674.PNG', 'frame_001675.PNG', 'frame_001676.PNG', 'frame_001677.PNG', 'frame_001678.PNG', 'frame_001679.PNG', 'frame_001680.PNG', 'frame_001681.PNG', 'frame_001682.PNG', 'frame_001683.PNG', 'frame_001684.PNG', 'frame_001685.PNG', 'frame_001686.PNG', 'frame_001687.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_001688.PNG', 'frame_001689.PNG', 'frame_001690.PNG', 'frame_001691.PNG', 'frame_001692.PNG'

 47%|████▋     | 140/296 [00:08<00:06, 25.42it/s]

('frame_001816.PNG', 'frame_001817.PNG', 'frame_001818.PNG', 'frame_001819.PNG', 'frame_001820.PNG', 'frame_001821.PNG', 'frame_001822.PNG', 'frame_001823.PNG', 'frame_001824.PNG', 'frame_001825.PNG', 'frame_001826.PNG', 'frame_001827.PNG', 'frame_001828.PNG', 'frame_001829.PNG', 'frame_001830.PNG', 'frame_001831.PNG', 'frame_001832.PNG', 'frame_001833.PNG', 'frame_001834.PNG', 'frame_001835.PNG', 'frame_001836.PNG', 'frame_001837.PNG', 'frame_001838.PNG', 'frame_001839.PNG', 'frame_001840.PNG', 'frame_001841.PNG', 'frame_001842.PNG', 'frame_001843.PNG', 'frame_001844.PNG', 'frame_001845.PNG', 'frame_001846.PNG', 'frame_001847.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_001848.PNG', 'frame_001849.PNG', 'frame_001850.PNG', 'frame_001851.PNG', 'frame_001852.PNG', 'frame_001853.PNG', 'frame_001854.PNG', 'frame_001855.PNG', 'frame_001856.PNG', 'frame_001857.PNG', 'frame_001858.PNG', 'frame_0

 49%|████▉     | 146/296 [00:08<00:05, 25.68it/s]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000014.PNG', 'frame_000015.PNG', 'frame_000016.PNG', 'frame_000017.PNG', 'frame_000018.PNG', 'frame_000019.PNG', 'frame_000020.PNG', 'frame_000021.PNG', 'frame_000022.PNG', 'frame_000023.PNG', 'frame_000024.PNG', 'frame_000025.PNG', 'frame_000026.PNG', 'frame_000027.PNG', 'frame_000028.PNG', 'frame_000029.PNG', 'frame_000030.PNG', 'frame_000031.PNG', 'frame_000032.PNG', 'frame_000033.PNG', 'frame_000034.PNG', 'frame_000035.PNG', 'frame_000036.PNG', 'frame_000037.PNG', 'frame_000038.PNG', 'frame_000039.PNG', 'frame_000040.PNG', 'frame_000041.PNG', 'frame_000042.PNG', 'frame_000043.PNG', 'frame_000044.PNG', 'frame_000045.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000046.PNG', 'frame_000047.PNG', 'frame_000048.PNG', 'frame_000049.PNG', 'frame_000050.PNG'

 51%|█████▏    | 152/296 [00:09<00:05, 25.58it/s]

('frame_000174.PNG', 'frame_000175.PNG', 'frame_000176.PNG', 'frame_000177.PNG', 'frame_000178.PNG', 'frame_000179.PNG', 'frame_000180.PNG', 'frame_000181.PNG', 'frame_000182.PNG', 'frame_000183.PNG', 'frame_000184.PNG', 'frame_000185.PNG', 'frame_000186.PNG', 'frame_000187.PNG', 'frame_000188.PNG', 'frame_000189.PNG', 'frame_000190.PNG', 'frame_000191.PNG', 'frame_000192.PNG', 'frame_000193.PNG', 'frame_000194.PNG', 'frame_000195.PNG', 'frame_000196.PNG', 'frame_000197.PNG', 'frame_000198.PNG', 'frame_000199.PNG', 'frame_000200.PNG', 'frame_000201.PNG', 'frame_000202.PNG', 'frame_000203.PNG', 'frame_000204.PNG', 'frame_000205.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000206.PNG', 'frame_000207.PNG', 'frame_000208.PNG', 'frame_000209.PNG', 'frame_000210.PNG', 'frame_000211.PNG', 'frame_000212.PNG', 'frame_000213.PNG', 'frame_000214.PNG', 'frame_000215.PNG', 'frame_000216.PNG', 'frame_0

 53%|█████▎    | 158/296 [00:09<00:05, 26.32it/s]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000366.PNG', 'frame_000367.PNG', 'frame_000368.PNG', 'frame_000369.PNG', 'frame_000370.PNG', 'frame_000371.PNG', 'frame_000372.PNG', 'frame_000373.PNG', 'frame_000374.PNG', 'frame_000375.PNG', 'frame_000376.PNG', 'frame_000377.PNG', 'frame_000378.PNG', 'frame_000379.PNG', 'frame_000380.PNG', 'frame_000381.PNG', 'frame_000382.PNG', 'frame_000383.PNG', 'frame_000384.PNG', 'frame_000385.PNG', 'frame_000386.PNG', 'frame_000387.PNG', 'frame_000388.PNG', 'frame_000389.PNG', 'frame_000390.PNG', 'frame_000391.PNG', 'frame_000392.PNG', 'frame_000393.PNG', 'frame_000394.PNG', 'frame_000395.PNG', 'frame_000396.PNG', 'frame_000397.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000398.PNG', 'frame_000399.PNG', 'frame_000400.PNG', 'frame_000401.PNG', 'frame_000402.PNG'

 55%|█████▌    | 164/296 [00:09<00:05, 25.75it/s]

('frame_000526.PNG', 'frame_000527.PNG', 'frame_000528.PNG', 'frame_000529.PNG', 'frame_000530.PNG', 'frame_000531.PNG', 'frame_000532.PNG', 'frame_000533.PNG', 'frame_000534.PNG', 'frame_000535.PNG', 'frame_000536.PNG', 'frame_000537.PNG', 'frame_000538.PNG', 'frame_000539.PNG', 'frame_000540.PNG', 'frame_000541.PNG', 'frame_000542.PNG', 'frame_000543.PNG', 'frame_000544.PNG', 'frame_000545.PNG', 'frame_000546.PNG', 'frame_000547.PNG', 'frame_000548.PNG', 'frame_000549.PNG', 'frame_000550.PNG', 'frame_000551.PNG', 'frame_000552.PNG', 'frame_000553.PNG', 'frame_000554.PNG', 'frame_000555.PNG', 'frame_000556.PNG', 'frame_000557.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000558.PNG', 'frame_000559.PNG', 'frame_000560.PNG', 'frame_000561.PNG', 'frame_000562.PNG', 'frame_000563.PNG', 'frame_000564.PNG', 'frame_000565.PNG', 'frame_000566.PNG', 'frame_000567.PNG', 'frame_000568.PNG', 'frame_0

 57%|█████▋    | 170/296 [00:09<00:04, 26.39it/s]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000718.PNG', 'frame_000719.PNG', 'frame_000720.PNG', 'frame_000721.PNG', 'frame_000722.PNG', 'frame_000723.PNG', 'frame_000724.PNG', 'frame_000725.PNG', 'frame_000726.PNG', 'frame_000727.PNG', 'frame_000728.PNG', 'frame_000729.PNG', 'frame_000730.PNG', 'frame_000731.PNG', 'frame_000732.PNG', 'frame_000733.PNG', 'frame_000734.PNG', 'frame_000735.PNG', 'frame_000736.PNG', 'frame_000737.PNG', 'frame_000738.PNG', 'frame_000739.PNG', 'frame_000740.PNG', 'frame_000741.PNG', 'frame_000742.PNG', 'frame_000743.PNG', 'frame_000744.PNG', 'frame_000745.PNG', 'frame_000746.PNG', 'frame_000747.PNG', 'frame_000748.PNG', 'frame_000749.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000750.PNG', 'frame_000751.PNG', 'frame_000752.PNG', 'frame_000753.PNG', 'frame_000754.PNG'

 58%|█████▊    | 173/296 [00:09<00:04, 25.86it/s]

('frame_000878.PNG', 'frame_000879.PNG', 'frame_000880.PNG', 'frame_000881.PNG', 'frame_000882.PNG', 'frame_000883.PNG', 'frame_000884.PNG', 'frame_000885.PNG', 'frame_000886.PNG', 'frame_000887.PNG', 'frame_000888.PNG', 'frame_000889.PNG', 'frame_000890.PNG', 'frame_000891.PNG', 'frame_000892.PNG', 'frame_000893.PNG', 'frame_000894.PNG', 'frame_000895.PNG', 'frame_000896.PNG', 'frame_000897.PNG', 'frame_000898.PNG', 'frame_000899.PNG', 'frame_000900.PNG', 'frame_000901.PNG', 'frame_000902.PNG', 'frame_000903.PNG', 'frame_000904.PNG', 'frame_000905.PNG', 'frame_000906.PNG', 'frame_000907.PNG', 'frame_000908.PNG', 'frame_000909.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000910.PNG', 'frame_000911.PNG', 'frame_000912.PNG', 'frame_000913.PNG', 'frame_000914.PNG', 'frame_000915.PNG', 'frame_000916.PNG', 'frame_000917.PNG', 'frame_000918.PNG', 'frame_000919.PNG', 'frame_000920.PNG', 'frame_0

 60%|██████    | 179/296 [00:10<00:04, 25.99it/s]

('frame_003809.PNG', 'frame_003810.PNG', 'frame_003811.PNG', 'frame_003812.PNG', 'frame_003813.PNG', 'frame_003814.PNG', 'frame_003815.PNG', 'frame_003816.PNG', 'frame_003817.PNG', 'frame_003818.PNG', 'frame_003819.PNG', 'frame_003820.PNG', 'frame_003821.PNG', 'frame_003822.PNG', 'frame_003823.PNG', 'frame_003824.PNG', 'frame_003825.PNG', 'frame_003826.PNG', 'frame_003827.PNG', 'frame_003828.PNG', 'frame_003829.PNG', 'frame_003830.PNG', 'frame_003831.PNG', 'frame_003832.PNG', 'frame_003833.PNG', 'frame_003834.PNG', 'frame_003835.PNG', 'frame_003836.PNG', 'frame_003837.PNG', 'frame_003838.PNG', 'frame_003839.PNG', 'frame_003840.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_003841.PNG', 'frame_003842.PNG', 'frame_003843.PNG', 'frame_003844.PNG', 'frame_003845.PNG', 'frame_003846.PNG', 'frame_003847.PNG', 'frame_003848.PNG', 'frame_003849.PNG', 'frame_003850.PNG', 'frame_003851.PNG', 'frame_0

 62%|██████▎   | 185/296 [00:10<00:04, 25.61it/s]

('frame_004001.PNG', 'frame_004002.PNG', 'frame_004003.PNG', 'frame_004004.PNG', 'frame_004005.PNG', 'frame_004006.PNG', 'frame_004007.PNG', 'frame_004008.PNG', 'frame_004009.PNG', 'frame_004010.PNG', 'frame_004011.PNG', 'frame_004012.PNG', 'frame_004013.PNG', 'frame_004014.PNG', 'frame_004015.PNG', 'frame_004016.PNG', 'frame_004017.PNG', 'frame_004018.PNG', 'frame_004019.PNG', 'frame_004020.PNG', 'frame_004021.PNG', 'frame_004022.PNG', 'frame_004023.PNG', 'frame_004024.PNG', 'frame_004025.PNG', 'frame_004026.PNG', 'frame_004027.PNG', 'frame_004028.PNG', 'frame_004029.PNG', 'frame_004030.PNG', 'frame_004031.PNG', 'frame_004032.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_004033.PNG', 'frame_004034.PNG', 'frame_004035.PNG', 'frame_004036.PNG', 'frame_004037.PNG', 'frame_004038.PNG', 'frame_004039.PNG', 'frame_004040.PNG', 'frame_004041.PNG', 'frame_004042.PNG', 'frame_004043.PNG', 'frame_0

 65%|██████▍   | 191/296 [00:10<00:04, 24.69it/s]

('frame_004161.PNG', 'frame_004162.PNG', 'frame_004163.PNG', 'frame_004164.PNG', 'frame_004165.PNG', 'frame_004166.PNG', 'frame_004167.PNG', 'frame_004168.PNG', 'frame_004169.PNG', 'frame_004170.PNG', 'frame_004171.PNG', 'frame_004172.PNG', 'frame_004173.PNG', 'frame_004174.PNG', 'frame_004175.PNG', 'frame_004176.PNG', 'frame_004177.PNG', 'frame_004178.PNG', 'frame_004179.PNG', 'frame_004180.PNG', 'frame_004181.PNG', 'frame_004182.PNG', 'frame_004183.PNG', 'frame_004184.PNG', 'frame_004185.PNG', 'frame_004186.PNG', 'frame_004187.PNG', 'frame_004188.PNG', 'frame_004189.PNG', 'frame_004190.PNG', 'frame_004191.PNG', 'frame_004192.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_004193.PNG', 'frame_004194.PNG', 'frame_004195.PNG', 'frame_004196.PNG', 'frame_004197.PNG', 'frame_004198.PNG', 'frame_004199.PNG', 'frame_004200.PNG', 'frame_004201.PNG', 'frame_004202.PNG', 'frame_004203.PNG', 'frame_0

 66%|██████▌   | 194/296 [00:10<00:04, 25.23it/s]

('frame_004321.PNG', 'frame_004322.PNG', 'frame_004323.PNG', 'frame_004324.PNG', 'frame_004325.PNG', 'frame_004326.PNG', 'frame_004327.PNG', 'frame_004328.PNG', 'frame_004329.PNG', 'frame_004330.PNG', 'frame_004331.PNG', 'frame_004332.PNG', 'frame_004333.PNG', 'frame_004334.PNG', 'frame_004335.PNG', 'frame_004336.PNG', 'frame_004337.PNG', 'frame_004338.PNG', 'frame_004339.PNG', 'frame_004340.PNG', 'frame_004341.PNG', 'frame_004342.PNG', 'frame_004343.PNG', 'frame_004344.PNG', 'frame_004345.PNG', 'frame_004346.PNG', 'frame_004347.PNG', 'frame_004348.PNG', 'frame_004349.PNG', 'frame_004350.PNG', 'frame_004351.PNG', 'frame_004352.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_004353.PNG', 'frame_004354.PNG', 'frame_004355.PNG', 'frame_004356.PNG', 'frame_004357.PNG', 'frame_004358.PNG', 'frame_004359.PNG', 'frame_004360.PNG', 'frame_004361.PNG', 'frame_004362.PNG', 'frame_004363.PNG', 'frame_0

 68%|██████▊   | 200/296 [00:10<00:04, 23.55it/s]

('frame_004481.PNG', 'frame_004482.PNG', 'frame_004483.PNG', 'frame_004484.PNG', 'frame_004485.PNG', 'frame_004486.PNG', 'frame_004487.PNG', 'frame_004488.PNG', 'frame_004489.PNG', 'frame_004490.PNG', 'frame_004491.PNG', 'frame_004492.PNG', 'frame_004493.PNG', 'frame_004494.PNG', 'frame_004495.PNG', 'frame_004496.PNG', 'frame_004497.PNG', 'frame_004498.PNG', 'frame_004499.PNG', 'frame_004500.PNG', 'frame_004501.PNG', 'frame_004502.PNG', 'frame_004503.PNG', 'frame_004504.PNG', 'frame_004505.PNG', 'frame_004506.PNG', 'frame_004507.PNG', 'frame_004508.PNG', 'frame_004509.PNG', 'frame_004510.PNG', 'frame_004511.PNG', 'frame_004512.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_004513.PNG', 'frame_004514.PNG', 'frame_004515.PNG', 'frame_004516.PNG', 'frame_004517.PNG', 'frame_004518.PNG', 'frame_004519.PNG', 'frame_004520.PNG', 'frame_004521.PNG', 'frame_004522.PNG', 'frame_004523.PNG', 'frame_0

 70%|██████▉   | 206/296 [00:11<00:03, 24.26it/s]

('frame_004641.PNG', 'frame_004642.PNG', 'frame_004643.PNG', 'frame_004644.PNG', 'frame_004645.PNG', 'frame_004646.PNG', 'frame_004647.PNG', 'frame_004648.PNG', 'frame_004649.PNG', 'frame_004650.PNG', 'frame_004651.PNG', 'frame_004652.PNG', 'frame_004653.PNG', 'frame_004654.PNG', 'frame_004655.PNG', 'frame_004656.PNG', 'frame_004657.PNG', 'frame_004658.PNG', 'frame_004659.PNG', 'frame_004660.PNG', 'frame_004661.PNG', 'frame_004662.PNG', 'frame_004663.PNG', 'frame_004664.PNG', 'frame_004665.PNG', 'frame_004666.PNG', 'frame_004667.PNG', 'frame_004668.PNG', 'frame_004669.PNG', 'frame_004670.PNG', 'frame_004671.PNG', 'frame_004672.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_004673.PNG', 'frame_004674.PNG', 'frame_004675.PNG', 'frame_004676.PNG', 'frame_004677.PNG', 'frame_004678.PNG', 'frame_004679.PNG', 'frame_004680.PNG', 'frame_004681.PNG', 'frame_004682.PNG', 'frame_004683.PNG', 'frame_0

 72%|███████▏  | 212/296 [00:11<00:03, 24.91it/s]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000101.PNG', 'frame_000102.PNG', 'frame_000103.PNG', 'frame_000104.PNG', 'frame_000105.PNG', 'frame_000106.PNG', 'frame_000107.PNG', 'frame_000108.PNG', 'frame_000109.PNG', 'frame_000110.PNG', 'frame_000111.PNG', 'frame_000112.PNG', 'frame_000113.PNG', 'frame_000114.PNG', 'frame_000115.PNG', 'frame_000116.PNG', 'frame_000117.PNG', 'frame_000118.PNG', 'frame_000119.PNG', 'frame_000120.PNG', 'frame_000121.PNG', 'frame_000122.PNG', 'frame_000123.PNG', 'frame_000124.PNG', 'frame_000125.PNG', 'frame_000126.PNG', 'frame_000127.PNG', 'frame_000128.PNG', 'frame_000129.PNG', 'frame_000130.PNG', 'frame_000131.PNG', 'frame_000132.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000133.PNG', 'frame_000134.PNG', 'frame_000135.PNG', 'frame_000136.PNG', 'frame_000137.PNG'

 73%|███████▎  | 215/296 [00:11<00:03, 24.94it/s]

('frame_000261.PNG', 'frame_000262.PNG', 'frame_000263.PNG', 'frame_000264.PNG', 'frame_000265.PNG', 'frame_000266.PNG', 'frame_000267.PNG', 'frame_000268.PNG', 'frame_000269.PNG', 'frame_000270.PNG', 'frame_000271.PNG', 'frame_000272.PNG', 'frame_000273.PNG', 'frame_000274.PNG', 'frame_000275.PNG', 'frame_000276.PNG', 'frame_000277.PNG', 'frame_000278.PNG', 'frame_000279.PNG', 'frame_000280.PNG', 'frame_000281.PNG', 'frame_000282.PNG', 'frame_000283.PNG', 'frame_000284.PNG', 'frame_000285.PNG', 'frame_000286.PNG', 'frame_000287.PNG', 'frame_000288.PNG', 'frame_000289.PNG', 'frame_000290.PNG', 'frame_000291.PNG', 'frame_000292.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000293.PNG', 'frame_000294.PNG', 'frame_000295.PNG', 'frame_000296.PNG', 'frame_000297.PNG', 'frame_000298.PNG', 'frame_000299.PNG', 'frame_000300.PNG', 'frame_000301.PNG', 'frame_000302.PNG', 'frame_000303.PNG', 'frame_0

 75%|███████▍  | 221/296 [00:11<00:02, 25.09it/s]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000453.PNG', 'frame_000454.PNG', 'frame_000455.PNG', 'frame_000456.PNG', 'frame_000457.PNG', 'frame_000458.PNG', 'frame_000459.PNG', 'frame_000460.PNG', 'frame_000461.PNG', 'frame_000462.PNG', 'frame_000463.PNG', 'frame_000464.PNG', 'frame_000465.PNG', 'frame_000466.PNG', 'frame_000467.PNG', 'frame_000468.PNG', 'frame_000469.PNG', 'frame_000470.PNG', 'frame_000471.PNG', 'frame_000472.PNG', 'frame_000473.PNG', 'frame_000474.PNG', 'frame_000475.PNG', 'frame_000476.PNG', 'frame_000477.PNG', 'frame_000478.PNG', 'frame_000479.PNG', 'frame_000480.PNG', 'frame_000481.PNG', 'frame_000482.PNG', 'frame_000483.PNG', 'frame_000484.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000485.PNG', 'frame_000486.PNG', 'frame_000487.PNG', 'frame_000488.PNG', 'frame_000489.PNG'

 77%|███████▋  | 227/296 [00:11<00:02, 25.33it/s]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000613.PNG', 'frame_000614.PNG', 'frame_000615.PNG', 'frame_000616.PNG', 'frame_000617.PNG', 'frame_000618.PNG', 'frame_000619.PNG', 'frame_000620.PNG', 'frame_000621.PNG', 'frame_000622.PNG', 'frame_000623.PNG', 'frame_000624.PNG', 'frame_000625.PNG', 'frame_000626.PNG', 'frame_000627.PNG', 'frame_000628.PNG', 'frame_000629.PNG', 'frame_000630.PNG', 'frame_000631.PNG', 'frame_000632.PNG', 'frame_000633.PNG', 'frame_000634.PNG', 'frame_000635.PNG', 'frame_000636.PNG', 'frame_000637.PNG', 'frame_000638.PNG', 'frame_000639.PNG', 'frame_000640.PNG', 'frame_000641.PNG', 'frame_000642.PNG', 'frame_000643.PNG', 'frame_000644.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000645.PNG', 'frame_000646.PNG', 'frame_000647.PNG', 'frame_000648.PNG', 'frame_000649.PNG'

 79%|███████▊  | 233/296 [00:12<00:02, 25.39it/s]

('frame_000923.PNG', 'frame_000924.PNG', 'frame_000925.PNG', 'frame_000926.PNG', 'frame_000927.PNG', 'frame_000928.PNG', 'frame_000929.PNG', 'frame_000930.PNG', 'frame_000931.PNG', 'frame_000932.PNG', 'frame_000933.PNG', 'frame_000934.PNG', 'frame_000935.PNG', 'frame_000936.PNG', 'frame_000937.PNG', 'frame_000938.PNG', 'frame_000939.PNG', 'frame_000940.PNG', 'frame_000941.PNG', 'frame_000942.PNG', 'frame_000943.PNG', 'frame_000944.PNG', 'frame_000945.PNG', 'frame_000946.PNG', 'frame_000947.PNG', 'frame_000948.PNG', 'frame_000949.PNG', 'frame_000950.PNG', 'frame_000951.PNG', 'frame_000952.PNG', 'frame_000953.PNG', 'frame_000954.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000955.PNG', 'frame_000956.PNG', 'frame_000957.PNG', 'frame_000958.PNG', 'frame_000959.PNG', 'frame_000960.PNG', 'frame_000961.PNG', 'frame_000962.PNG', 'frame_000963.PNG', 'frame_000964.PNG', 'frame_000965.PNG', 'frame_0

 80%|███████▉  | 236/296 [00:12<00:02, 24.47it/s]

('frame_001083.PNG', 'frame_001084.PNG', 'frame_001085.PNG', 'frame_001086.PNG', 'frame_001087.PNG', 'frame_001088.PNG', 'frame_001089.PNG', 'frame_001090.PNG', 'frame_001091.PNG', 'frame_001092.PNG', 'frame_001093.PNG', 'frame_001094.PNG', 'frame_001095.PNG', 'frame_001096.PNG', 'frame_001097.PNG', 'frame_001098.PNG', 'frame_001099.PNG', 'frame_001100.PNG', 'frame_001101.PNG', 'frame_001102.PNG', 'frame_001103.PNG', 'frame_001104.PNG', 'frame_001105.PNG', 'frame_001106.PNG', 'frame_001107.PNG', 'frame_001108.PNG', 'frame_001109.PNG', 'frame_001110.PNG', 'frame_001111.PNG', 'frame_001112.PNG', 'frame_001113.PNG', 'frame_001114.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_001115.PNG', 'frame_001116.PNG', 'frame_001117.PNG', 'frame_001118.PNG', 'frame_001119.PNG', 'frame_001120.PNG', 'frame_001121.PNG', 'frame_001122.PNG', 'frame_001123.PNG', 'frame_001124.PNG', 'frame_001125.PNG', 'frame_0

 82%|████████▏ | 242/296 [00:12<00:02, 22.18it/s]

('frame_001243.PNG', 'frame_001244.PNG', 'frame_001245.PNG', 'frame_001246.PNG', 'frame_001247.PNG', 'frame_000027.PNG', 'frame_000028.PNG', 'frame_000029.PNG', 'frame_000030.PNG', 'frame_000031.PNG', 'frame_000032.PNG', 'frame_000033.PNG', 'frame_000034.PNG', 'frame_000035.PNG', 'frame_000036.PNG', 'frame_000037.PNG', 'frame_000038.PNG', 'frame_000039.PNG', 'frame_000040.PNG', 'frame_000041.PNG', 'frame_000042.PNG', 'frame_000043.PNG', 'frame_000044.PNG', 'frame_000045.PNG', 'frame_000046.PNG', 'frame_000047.PNG', 'frame_000048.PNG', 'frame_000049.PNG', 'frame_000050.PNG', 'frame_000051.PNG', 'frame_000052.PNG', 'frame_000053.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000054.PNG', 'frame_000055.PNG', 'frame_000056.PNG', 'frame_000057.PNG', 'frame_000058.PNG', 'frame_000059.PNG', 'frame_000060.PNG', 'frame_000061.PNG', 'frame_000062.PNG', 'frame_000063.PNG', 'frame_000064.PNG', 'frame_0

 83%|████████▎ | 245/296 [00:12<00:02, 21.67it/s]

('frame_000150.PNG', 'frame_000151.PNG', 'frame_000152.PNG', 'frame_000153.PNG', 'frame_000154.PNG', 'frame_000155.PNG', 'frame_000156.PNG', 'frame_000157.PNG', 'frame_000158.PNG', 'frame_000159.PNG', 'frame_000160.PNG', 'frame_000161.PNG', 'frame_000162.PNG', 'frame_000163.PNG', 'frame_000164.PNG', 'frame_000165.PNG', 'frame_000166.PNG', 'frame_000167.PNG', 'frame_000168.PNG', 'frame_000169.PNG', 'frame_000170.PNG', 'frame_000171.PNG', 'frame_000172.PNG', 'frame_000173.PNG', 'frame_000174.PNG', 'frame_000175.PNG', 'frame_000176.PNG', 'frame_000177.PNG', 'frame_000178.PNG', 'frame_000179.PNG', 'frame_000180.PNG', 'frame_000181.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000182.PNG', 'frame_000183.PNG', 'frame_000184.PNG', 'frame_000185.PNG', 'frame_000186.PNG', 'frame_000187.PNG', 'frame_000188.PNG', 'frame_000189.PNG', 'frame_000190.PNG', 'frame_000191.PNG', 'frame_000192.PNG', 'frame_0

 85%|████████▍ | 251/296 [00:13<00:02, 22.46it/s]

('frame_000322.PNG', 'frame_000323.PNG', 'frame_000324.PNG', 'frame_000325.PNG', 'frame_000353.PNG', 'frame_000354.PNG', 'frame_000355.PNG', 'frame_000356.PNG', 'frame_000357.PNG', 'frame_000358.PNG', 'frame_000359.PNG', 'frame_000360.PNG', 'frame_000361.PNG', 'frame_000362.PNG', 'frame_000363.PNG', 'frame_000364.PNG', 'frame_000365.PNG', 'frame_000366.PNG', 'frame_000367.PNG', 'frame_000368.PNG', 'frame_000369.PNG', 'frame_000370.PNG', 'frame_000371.PNG', 'frame_000372.PNG', 'frame_000373.PNG', 'frame_000374.PNG', 'frame_000375.PNG', 'frame_000376.PNG', 'frame_000377.PNG', 'frame_000378.PNG', 'frame_000379.PNG', 'frame_000380.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000381.PNG', 'frame_000382.PNG', 'frame_000383.PNG', 'frame_000384.PNG', 'frame_000385.PNG', 'frame_000386.PNG', 'frame_000387.PNG', 'frame_000388.PNG', 'frame_000389.PNG', 'frame_000390.PNG', 'frame_000391.PNG', 'frame_0

 87%|████████▋ | 257/296 [00:13<00:01, 23.79it/s]

('frame_000509.PNG', 'frame_000510.PNG', 'frame_000511.PNG', 'frame_000512.PNG', 'frame_000513.PNG', 'frame_000514.PNG', 'frame_000515.PNG', 'frame_000516.PNG', 'frame_000517.PNG', 'frame_000518.PNG', 'frame_000519.PNG', 'frame_000520.PNG', 'frame_000521.PNG', 'frame_000522.PNG', 'frame_000523.PNG', 'frame_000524.PNG', 'frame_000525.PNG', 'frame_000526.PNG', 'frame_000527.PNG', 'frame_000528.PNG', 'frame_000529.PNG', 'frame_000530.PNG', 'frame_000531.PNG', 'frame_000532.PNG', 'frame_000533.PNG', 'frame_000534.PNG', 'frame_000535.PNG', 'frame_000536.PNG', 'frame_000537.PNG', 'frame_000538.PNG', 'frame_000539.PNG', 'frame_000540.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000541.PNG', 'frame_000542.PNG', 'frame_000543.PNG', 'frame_000544.PNG', 'frame_000545.PNG', 'frame_000546.PNG', 'frame_000547.PNG', 'frame_000548.PNG', 'frame_000549.PNG', 'frame_000550.PNG', 'frame_000551.PNG', 'frame_0

 88%|████████▊ | 260/296 [00:13<00:01, 23.17it/s]

('frame_000746.PNG', 'frame_000747.PNG', 'frame_000748.PNG', 'frame_000749.PNG', 'frame_000750.PNG', 'frame_000751.PNG', 'frame_000752.PNG', 'frame_000753.PNG', 'frame_000754.PNG', 'frame_000755.PNG', 'frame_000756.PNG', 'frame_000757.PNG', 'frame_000758.PNG', 'frame_000759.PNG', 'frame_000760.PNG', 'frame_000761.PNG', 'frame_000762.PNG', 'frame_000763.PNG', 'frame_000764.PNG', 'frame_000765.PNG', 'frame_000766.PNG', 'frame_000767.PNG', 'frame_000768.PNG', 'frame_000769.PNG', 'frame_000770.PNG', 'frame_000771.PNG', 'frame_000772.PNG', 'frame_000773.PNG', 'frame_000774.PNG', 'frame_000775.PNG', 'frame_000776.PNG', 'frame_000777.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000778.PNG', 'frame_000779.PNG', 'frame_000780.PNG', 'frame_000781.PNG', 'frame_000782.PNG', 'frame_000783.PNG', 'frame_000784.PNG', 'frame_000785.PNG', 'frame_000786.PNG', 'frame_000829.PNG', 'frame_000830.PNG', 'frame_0

 90%|████████▉ | 266/296 [00:13<00:01, 23.16it/s]

('frame_000948.PNG', 'frame_000949.PNG', 'frame_000950.PNG', 'frame_000951.PNG', 'frame_000952.PNG', 'frame_000953.PNG', 'frame_000954.PNG', 'frame_000955.PNG', 'frame_000956.PNG', 'frame_000957.PNG', 'frame_000958.PNG', 'frame_000959.PNG', 'frame_000960.PNG', 'frame_000961.PNG', 'frame_000962.PNG', 'frame_000963.PNG', 'frame_000964.PNG', 'frame_000965.PNG', 'frame_000966.PNG', 'frame_000967.PNG', 'frame_000968.PNG', 'frame_000969.PNG', 'frame_000970.PNG', 'frame_000971.PNG', 'frame_000972.PNG', 'frame_000973.PNG', 'frame_000974.PNG', 'frame_000975.PNG', 'frame_000976.PNG', 'frame_000977.PNG', 'frame_000978.PNG', 'frame_000979.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_000980.PNG', 'frame_000981.PNG', 'frame_000982.PNG', 'frame_000983.PNG', 'frame_000984.PNG', 'frame_000985.PNG', 'frame_000986.PNG', 'frame_000987.PNG', 'frame_000988.PNG', 'frame_000989.PNG', 'frame_000990.PNG', 'frame_0

 92%|█████████▏| 272/296 [00:13<00:01, 23.26it/s]

('frame_001163.PNG', 'frame_001164.PNG', 'frame_001165.PNG', 'frame_001166.PNG', 'frame_001167.PNG', 'frame_001168.PNG', 'frame_001169.PNG', 'frame_001170.PNG', 'frame_001171.PNG', 'frame_001172.PNG', 'frame_001173.PNG', 'frame_001174.PNG', 'frame_001175.PNG', 'frame_001176.PNG', 'frame_001177.PNG', 'frame_001178.PNG', 'frame_001179.PNG', 'frame_001180.PNG', 'frame_001181.PNG', 'frame_001266.PNG', 'frame_001267.PNG', 'frame_001268.PNG', 'frame_001269.PNG', 'frame_001270.PNG', 'frame_001271.PNG', 'frame_001272.PNG', 'frame_001273.PNG', 'frame_001274.PNG', 'frame_001275.PNG', 'frame_001276.PNG', 'frame_001277.PNG', 'frame_001278.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_001279.PNG', 'frame_001280.PNG', 'frame_001281.PNG', 'frame_001282.PNG', 'frame_001283.PNG', 'frame_001284.PNG', 'frame_001285.PNG', 'frame_001286.PNG', 'frame_001287.PNG', 'frame_001288.PNG', 'frame_001289.PNG', 'frame_0

 93%|█████████▎| 275/296 [00:14<00:00, 23.85it/s]

('frame_001483.PNG', 'frame_001484.PNG', 'frame_001485.PNG', 'frame_001486.PNG', 'frame_001487.PNG', 'frame_001488.PNG', 'frame_001489.PNG', 'frame_001490.PNG', 'frame_001491.PNG', 'frame_001492.PNG', 'frame_001493.PNG', 'frame_001494.PNG', 'frame_001495.PNG', 'frame_001496.PNG', 'frame_001497.PNG', 'frame_001498.PNG', 'frame_001499.PNG', 'frame_001500.PNG', 'frame_001501.PNG', 'frame_001502.PNG', 'frame_001503.PNG', 'frame_001504.PNG', 'frame_001505.PNG', 'frame_001506.PNG', 'frame_001507.PNG', 'frame_001508.PNG', 'frame_001509.PNG', 'frame_001510.PNG', 'frame_001511.PNG', 'frame_001512.PNG', 'frame_001513.PNG', 'frame_001514.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_001515.PNG', 'frame_001516.PNG', 'frame_001517.PNG', 'frame_001518.PNG', 'frame_001519.PNG', 'frame_001520.PNG', 'frame_001521.PNG', 'frame_001522.PNG', 'frame_001523.PNG', 'frame_001524.PNG', 'frame_001525.PNG', 'frame_0

 95%|█████████▍| 281/296 [00:14<00:00, 22.69it/s]

('frame_001709.PNG', 'frame_001710.PNG', 'frame_001743.PNG', 'frame_001744.PNG', 'frame_001745.PNG', 'frame_001746.PNG', 'frame_001747.PNG', 'frame_001748.PNG', 'frame_001749.PNG', 'frame_001750.PNG', 'frame_001751.PNG', 'frame_001752.PNG', 'frame_001753.PNG', 'frame_001754.PNG', 'frame_001755.PNG', 'frame_001756.PNG', 'frame_001757.PNG', 'frame_001758.PNG', 'frame_001759.PNG', 'frame_001760.PNG', 'frame_001761.PNG', 'frame_001762.PNG', 'frame_001763.PNG', 'frame_001764.PNG', 'frame_001796.PNG', 'frame_001797.PNG', 'frame_001798.PNG', 'frame_001799.PNG', 'frame_001800.PNG', 'frame_001801.PNG', 'frame_001802.PNG', 'frame_001803.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_001804.PNG', 'frame_001805.PNG', 'frame_001806.PNG', 'frame_001807.PNG', 'frame_001808.PNG', 'frame_001809.PNG', 'frame_001810.PNG', 'frame_001811.PNG', 'frame_001812.PNG', 'frame_001813.PNG', 'frame_001814.PNG', 'frame_0

 96%|█████████▌| 284/296 [00:14<00:00, 22.49it/s]

('frame_001963.PNG', 'frame_001964.PNG', 'frame_001965.PNG', 'frame_001966.PNG', 'frame_001967.PNG', 'frame_001968.PNG', 'frame_001969.PNG', 'frame_001970.PNG', 'frame_001971.PNG', 'frame_001972.PNG', 'frame_001973.PNG', 'frame_001974.PNG', 'frame_001975.PNG', 'frame_001976.PNG', 'frame_001977.PNG', 'frame_001978.PNG', 'frame_001979.PNG', 'frame_001980.PNG', 'frame_001981.PNG', 'frame_001982.PNG', 'frame_001983.PNG', 'frame_001984.PNG', 'frame_001985.PNG', 'frame_001986.PNG', 'frame_001987.PNG', 'frame_001988.PNG', 'frame_001989.PNG', 'frame_001990.PNG', 'frame_001991.PNG', 'frame_001992.PNG', 'frame_001993.PNG', 'frame_001994.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_001995.PNG', 'frame_001996.PNG', 'frame_001997.PNG', 'frame_001998.PNG', 'frame_001999.PNG', 'frame_002000.PNG', 'frame_002001.PNG', 'frame_002002.PNG', 'frame_002003.PNG', 'frame_002004.PNG', 'frame_002005.PNG', 'frame_0

 98%|█████████▊| 290/296 [00:14<00:00, 22.87it/s]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_002194.PNG', 'frame_002195.PNG', 'frame_002196.PNG', 'frame_002197.PNG', 'frame_002198.PNG', 'frame_002199.PNG', 'frame_002200.PNG', 'frame_002201.PNG', 'frame_002202.PNG', 'frame_002203.PNG', 'frame_002204.PNG', 'frame_002205.PNG', 'frame_002206.PNG', 'frame_002207.PNG', 'frame_002208.PNG', 'frame_002209.PNG', 'frame_002210.PNG', 'frame_002211.PNG', 'frame_002212.PNG', 'frame_002213.PNG', 'frame_002214.PNG', 'frame_002215.PNG', 'frame_002216.PNG', 'frame_002217.PNG', 'frame_002218.PNG', 'frame_002219.PNG', 'frame_002220.PNG', 'frame_002221.PNG', 'frame_002222.PNG', 'frame_002223.PNG', 'frame_002224.PNG', 'frame_002225.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_002226.PNG', 'frame_002227.PNG', 'frame_002228.PNG', 'frame_002229.PNG', 'frame_002230.PNG'

100%|██████████| 296/296 [00:14<00:00, 19.78it/s]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_002457.PNG', 'frame_002458.PNG', 'frame_002459.PNG', 'frame_002460.PNG', 'frame_002461.PNG', 'frame_002462.PNG', 'frame_002463.PNG', 'frame_002464.PNG', 'frame_002465.PNG', 'frame_002466.PNG', 'frame_002467.PNG', 'frame_002468.PNG', 'frame_002469.PNG', 'frame_002470.PNG', 'frame_002471.PNG', 'frame_002472.PNG', 'frame_002473.PNG', 'frame_002474.PNG', 'frame_002475.PNG', 'frame_002476.PNG', 'frame_002477.PNG', 'frame_002478.PNG', 'frame_002479.PNG', 'frame_002480.PNG', 'frame_002481.PNG', 'frame_002482.PNG', 'frame_002483.PNG', 'frame_002484.PNG', 'frame_002485.PNG', 'frame_002486.PNG', 'frame_002487.PNG', 'frame_002488.PNG') tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1], device='cuda:0')
('frame_002489.PNG', 'frame_002490.PNG', 'frame_002491.PNG', 'frame_002492.PNG', 'frame_002539.PNG'